### ISSUE TITLE
Master Progress Tracker for CRAN Complete Submission

### ISSUE THREAD

**Issue by lukesonnet** [DeclareDesign/estimatr#48]
This is a roadmap to CRAN bliss.

**Estimators**
- [x] `horvitz_thompson()` issue #18
    - [X] Implement Young's inequality and constant effects variance estimators
    - [x] Implement support for blocked and clustered designs
    - [x] ~~~Implement support for complete randomized designs where there are some joint probabilities == 0 within clusters~~~ Warn if variance is < 0, which is possible!
    - [x] Implement function to take any arbitrary permutation matrix and build condition probability matrix
    - [x] Change how data is processed from `declare_ra()` or `data`, depends partially on DeclareDesign/randomizr#26
        - [x] Need to add support for learning condition_pr_mat from blocked designs
    - [x] Macartan feedback
    - [x] Resolving "constant" effects estimator
    - [x] Documentation
    - [x] Tests
- [x] `difference_in_means()` issue #12 
    - [X] Support for clustered designs
    - [x] **Not supporting** ~Support for learning from `declare_ra()` issue #29~
    - [x] Confirm weighted variance is ~correct~, see #15 
    - [x] Confirm dof corrections for clustered and blocked designs
    - [x] Documentation
    - [x] Tests
- [x] `lm_robust()` 
    - [X] Implement clubSandwich variance (support for cluster-level dummies + weights in cluster robust inference)
    - [x] **Not supporting** ~Support for learning from `declare_ra()` issue #29~
    - [x] Check weights with the stata cluster robust variance estimation
    - [x] Move over to RcppEigen and support rank-deficient X #53 
    - [x] Documentation
    - [x] Tests
- [x] `lm_lin()`
    - [x] Multi-valued treatments - issue #66 
    - [x] Documentation

**Package wide**
- [x] Vignette - issue #10 
- [x] Benchmarking vignette
- [x] Style
- [x] ~Stargazable output - issue #7~ post-CRAN
- [x] Margins support - issue #63
- [x] Predict method for lm_robust and lm_lin
- [x] Jasper feedback
- [x] Overall coverage
- [x] Overall error handling - issue #11 
- [x] Check `tidy` collision with tidyverse/broom
- [x] Naming of `cluster_variable_name` arguments - issue #47 

**CRAN Submission Prep**
- [x] Look up any checks needed besides the default R build/check process
   - [x] WinBuilder
- [x] Confirm licenses, copyright statements, and other submission metadata
